# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='公告内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_image', models.ImageField(upload_to='live', verbose_name='展示图片')),
                ('name', models.CharField(max_length=100, verbose_name='机构名')),
                ('anchor_count', models.IntegerField(blank=True, verbose_name='主播数')),
                ('url', models.URLField(verbose_name='播放链接')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '直播平台',
                'verbose_name_plural': '直播平台',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='版本号')),
                ('mark', models.TextField(blank=True, verbose_name='版本更新提示')),
                ('update_url', models.URLField(verbose_name='更新地址')),
            ],
            options={
                'verbose_name': '版本',
                'verbose_name_plural': '版本',
                'ordering': ['version'],
            },
        ),
    ]
