# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='summary',
            field=models.TextField(default='', verbose_name='平台简介'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='live',
            name='show_image',
            field=models.ImageField(upload_to='media/live', verbose_name='展示图片'),
        ),
    ]
