# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171117_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='url',
            field=models.CharField(max_length=1000, verbose_name='播放链接'),
        ),
    ]
