# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 01:45
from __future__ import unicode_literals

import agent.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='账号')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机')),
                ('wechat', models.CharField(blank=True, max_length=50, verbose_name='微信')),
                ('e_mail', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('agent_class', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='VIP等级')),
                ('consume_point', models.IntegerField(default=0, verbose_name='点数')),
                ('invite_code', models.CharField(default=agent.models.Agent.get_invite, max_length=6, verbose_name='邀请码')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.Agent', verbose_name='上级代理')),
            ],
            options={
                'verbose_name': '代理',
                'verbose_name_plural': '代理',
                'ordering': ['agent_class'],
            },
        ),
        migrations.CreateModel(
            name='Carmel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=agent.models.Carmel.get_carmel, max_length=32, verbose_name='卡密')),
                ('type_class', models.CharField(choices=[('空卡', '空卡'), ('月卡', '月卡'), ('季卡', '季卡'), ('年卡', '年卡')], max_length=20, verbose_name='类型')),
                ('point', models.SmallIntegerField(default=agent.models.Carmel.get_carmel, editable=False, verbose_name='点数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '卡密',
                'verbose_name_plural': '卡密',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20, verbose_name='手机')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('vip_class', models.CharField(choices=[('注册会员', '注册会员'), ('月度会员', '月度会员'), ('季度会员', '季度会员'), ('年度会员', '年度会员')], default='注册会员', max_length=20, verbose_name='会员等级')),
                ('vip_date', models.DateTimeField(auto_now_add=True, verbose_name='VIP到期时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.Agent', verbose_name='推荐人')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
                'ordering': ['-create_time'],
            },
        ),
    ]
