# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmel',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未使用'), (1, '已使用')], default=0, editable=False, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='手机'),
        ),
    ]
