# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_auto_20171113_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmel',
            name='type_class',
            field=models.CharField(choices=[('空卡', '空卡 -- 0'), ('月卡', '月卡 -- 1'), ('季卡', '季卡 -- 2'), ('年卡', '年卡 -- 4')], max_length=20, verbose_name='类型'),
        ),
    ]
